// Generated by gfwlist2pac in precise mode
// https://github.com/clowwindy/gfwlist2pac

// var names = [];
// var proxies = [];
// var rules = [[]];

var matcheres = [];
var direct = 'DIRECT;';

for (var i = 0; i < proxies.length; i++) {
	matcheres[i] = new CombinedMatcher();
	for (var j = 0; j < rules[i].length; j++) {
		matcheres[i].add(Filter.fromText(rules[i][j]));
	}
}

function FindProxyForURL(url, host) {
	for (var i = 0; i < proxies.length; i++) {
		if (matcheres[i].matchesAny(url, host) instanceof BlockingFilter) {
			return proxies[i];
		}
	}
	return direct;
}
